[project]
name = "mywheels-scraper"
version = "0.1.0"
description = "Collect invoices' history from MyWheels"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "playwright>=1.48.0",
    "pydantic>=2.9.2",
    "pytest-playwright>=0.5.2",
    "pytest>=8.3.3",
]
